---
# oracle_java8

- name: what java8_rpm
  debug:
    msg: "{{ java8_rpms }}"

- name: Update apt cache.
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - java8
    - java8_install

- name: Ensure Java is installed.
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ java8_apts }}"

- name: Ensure Java is installed.
  when: ansible_os_family == 'RedHat'
  yum: "name={{ item }} state=installed"
  retries: 5
  with_items: "{{ java8_rpms }}"

- name: 'set java_top on Debian'
  become: yes
  set_fact:
    java8_top: '/usr/lib/jvm'
  tags:
    - java8
    - java8_install
    - java8_profile
    - java8_test
    - java8_alternatives
    - test
    - ant_test
    - maven_test
    - gradle_test

- name: 'make sure java_top exists'
  become: yes
  file: path={{ java8_top }} state=directory owner=root mode=0755
  tags:
    - java8

- name: 'this is JAVA_HOME'
  set_fact:
    java8_home: "{{ java8_top }}/{{ java_name }}"
    tags:
    - java8_test
    - test
    - ant_test
    - maven_test
    - gradle_test

- name: 'this is JAVA_HOME'
  debug:
    msg: "{{ java8_home }}"
  tags:
    - java8
    - java8_test
    - test
    - ant_test
    - maven_test
    - gradle_test

- name: 'install java8 facts'
  template:
    src: java8.fact
    dest: /etc/ansible/facts.d/java8.fact
    owner: root
    group: root
    mode: 0644
  tags:
    - java8

- name: 'fix JAVA_HOME'
  become: yes
  template:
    src: java.sh
    dest: /etc/profile.d/java.sh
  tags:
    - java8
    - java8_profile
