---

- name: setup
  become: no
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - './Whoami.java'
    - './Whoami.class'
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: smoke test java runtime
  become: no
  command: "{{ java8_top }}/java/bin/java -version"
  changed_when: no
  ignore_errors: "{{ continue_on_error | default(True) }}"
  register: java
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: verify java version
  become: no
  debug: msg="java ?? {{ java.stderr }}"
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: copy java source for tests
  become: no
  copy:
    src: Whoami.java
    dest: "~"
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: functional test Java compiler
  become: no
  command: "{{ java8_top }}/java/bin/javac Whoami.java"
  register: java_compile
  changed_when: "java_compile.rc == 0"
  failed_when: "java_compile.rc != 0"
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: functional test Java runtime
  become: no
  command: "java Whoami"
  changed_when: no
  ignore_errors: "{{ continue_on_error | default(True) }}"
  register: java8_class
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: verify bytecode version
  become: no
  command: "file Whoami.class Whoami.java"
  no_log: yes
  changed_when: no
  ignore_errors: "{{ continue_on_error | default(True) }}"
  register: java8_class
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: display bytecode version
  become: no
  debug: msg="{{ java8_class.stdout_lines }}"
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test

- name: teardown
  become: no
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - './Whoami.java'
    - './Whoami.class'
  tags:
    - oracle_java8
    - java8
    - java8_test
    - test
